site_name: OORAG
theme:
  name: material
  highlightjs: true  # 如果需要语法高亮
plugins:
  - search:
      lang:
        - en
        - zh
nav:
    - 首页: index.md
    - loader介绍:
      - 基本loader介绍: loader介绍/基本loader介绍.md
      - ocr_loader介绍: loader介绍/ocr_loader介绍.md
    - chunker介绍:
      - chunker介绍: chunker介绍/chunker介绍.md
    - embedder介绍:
      - bgem3介绍: embedder介绍/bgem3介绍.md
      - m3e介绍: embedder介绍/m3e介绍.md
    - llm介绍:
      - qwen2介绍: llm介绍/qwen2介绍.md
    - 如何部署: 如何部署.md

